name: Deploy to GCP VM (Docker Compose - SSH only)

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      deploy_dir:
        description: "Remote deploy dir (fallback to DEPLOY_DIR secret)"
        required: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sanity check secrets
        run: |
          test -n "${{ secrets.SSH_HOST }}" || (echo "SSH_HOST empty" && exit 1)
          test -n "${{ secrets.SSH_USER }}" || (echo "SSH_USER empty" && exit 1)
          test -n "${{ secrets.SSH_KEY }}"  || (echo "SSH_KEY empty"  && exit 1)
          test -n "${{ secrets.DEPLOY_DIR }}" || echo "DEPLOY_DIR not set (will rely on input)"

      - name: Deploy via SSH (docker compose)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            set -euo pipefail

            DEPLOY_DIR="${{ github.event.inputs.deploy_dir }}"
            if [ -z "$DEPLOY_DIR" ]; then DEPLOY_DIR="${{ secrets.DEPLOY_DIR }}"; fi
            if [ -z "$DEPLOY_DIR" ]; then echo "::error::DEPLOY_DIR not provided"; exit 1; fi

            echo "Using DEPLOY_DIR: $DEPLOY_DIR"
            sudo sh -c "
              cd $DEPLOY_DIR
              git fetch origin
              git reset --hard origin/master
              docker compose pull || true
              docker compose up -d
            "

            echo "✅ Deploy success"
